### PR TITLE
Create e2e tests for client-side navigation

### PR DESCRIPTION
**Pull request by SantosGuillamot**
As part of the pull request to [Fetch scripts in the <head> on client-side navigations](https://github.com/WordPress/block-interactivity-experiments/pull/164), I'm adding e2e to check that client-side navigation, and new styles and scripts work correctly. Some aspects to consider:

* I had to modify the WebPack config to bundle separate css files so we can check new `<link src="...">` after CSN. Let me know if that's not correct.
* There are a lot of files changed because I modify the folder structure to include page-1 and page-2, each one with a different `store.js` and `style.css` files.
* What is being checked right now:
  * Navigation is made in the client.
  * Content is updated after navigation.
  * Old content is removed after navigation.
  * It applies new styles after navigation.
  * It removes old styles after navigation.
  * It applies new scripts after navigation.

EDIT: ~~I don't how to ensure that the navigation is happening in the browser and that it is not doing a page refresh. Any ideas?~~ Done [here](https://github.com/WordPress/block-interactivity-experiments/pull/185#issuecomment-1478157870).

### CODE REVIEW

**Comment by michalczaplinski** [comment]
Do you want to merge this branch into the `fetch-scripts` branch?  Or do you want to first merge the `fetch-scripts` into `main-wp-directives-plugin` and then merge this branch? 

I think that it's the first one but I'm not 100% sure 🙂

**Comment by michalczaplinski** [comment]
To be honest, I would prefer to merge the https://github.com/WordPress/block-interactivity-experiments/pull/164 as soon as we've confirmed that it works with the WP Movies Demo so as not to delay publishing the blog post, regardless of whether it has e2e tests or not 🙂 .

**Comment by michalczaplinski** [comment]
> I don't how to ensure that the navigation is happening in the browser and that it is not doing a page refresh. Any ideas?

Do you mean that the e2e tests should do client-side navigations instead of a full page refresh? I think they should already do that since we include the `<meta itemprop="wp-client-side-navigation" content="active" />` right? Or did you mean something else?

We have one test failure here, BTW:

```
Running 1 test using 1 worker
line.js:37
  1) [chromium] › specs/csn.spec.ts:37:6 › toVdom - full › it should apply new scripts after navigation 

    Error: expect(received).toBeVisible()
    Call log:
      - expect.toBeVisible with timeout 5000ms
      - waiting for getByTestId('show when newValue is true')
      -   unexpected value "hidden"
      - waiting for getByTestId('show when newValue is true')
      -   unexpected value "hidden"
      -   locator resolved to <div _wrapped="true" id="new-show-div" data-testid="s…>…</div>
      -   unexpected value "hidden"
      -   locator resolved to <div _wrapped="true" id="new-show-div" data-testid="s…>…</div>
      -   unexpected value "hidden"
      -   unexpected value "hidden"
      -   unexpected value "hidden"
      -   unexpected value "hidden"
      -   unexpected value "hidden"
      -   unexpected value "hidden"


      40 | 		await page.getByTestId('csn-next-page').click();
      41 | 		const el = page.getByTestId('show when newValue is true');
    > 42 | 		await expect(el).toBeVisible();
         | 		                 ^
      43 | 		await page.getByTestId('toggle newValue').click();
      44 | 		await expect(el).toBeHidden();
      45 | 	});
 ```

I've started debugging it but didn't get far since it was already late. I'll have to look again tomorrow.

**Comment by SantosGuillamot** [comment]
> Do you want to merge this branch into the fetch-scripts branch? Or do you want to first merge the fetch-scripts into main-wp-directives-plugin and then merge this branch?

In my opinion, we should aim to have tests to cover the new functionalities that we add.

Actually, I started this pull request to add e2e tests for client-side navigation because **the [Fetch scripts in the <head> on client-side navigations](https://github.com/WordPress/block-interactivity-experiments/pull/164) PR is passing the tests, it is approved, but doesn't seem to be working**.

Indeed, one test is failing in this PR because we are not fetching the scripts after client-side navigation properly. I believe we need to fetch not only the `<head>` but also the `<body>` as explained [here](https://github.com/WordPress/block-interactivity-experiments/pull/164#issuecomment-1473813079). Once that is solved, these tests should pass if I am not mistaken.

**Comment by SantosGuillamot** [comment]
> Do you mean that the e2e tests should do client-side navigations instead of a full page refresh? I think they should already do that since we include the <meta itemprop="wp-client-side-navigation" content="active" /> right? Or did you mean something else?

Yes, they are doing that. I just wanted to add some tests with Playwright to ensure that is happening. If we break the client-side-navigation somehow, tests could pass but maybe it isn't working as expected.

**Comment by luisherranz** [comment]
> the Fetch scripts in the on client-side navigations PR is passing the tests, it is approved, but doesn't seem to be working

If you mean my review, I reviewed the PR when Michal opened it, but I didn't approve it yet.

> In my opinion, we should aim to have tests to cover the new functionalities that we add.

I agree 🙂

> I don't how to ensure that the navigation is happening in the browser and that it is not doing a page refresh. Any ideas?

What about adding a variable to `window` before you navigate, and then checking if it still exists? If it doesn't exist, it means it did a full refresh.

> What is being checked right now:
>
> - Content is updated after navigation.
> - Old content is removed after navigation.
> - It applies new styles after navigation.
> - It applies new scripts after navigation.

We can also ensure that styles that are only present on the initial page are removed.

**Comment by SantosGuillamot** [comment]
> If you mean my review, I reviewed the PR when Michal opened it, but I didn't approve it yet.

Oh, sorry! I saw the green button on the "Merge pull request" and I assumed it had been approved, but we don't have that requirement in this repo.

> What about adding a variable to window before you navigate, and then checking if it still exists? If it doesn't exist, it means it did a full refresh.

I can try that 🙂 

> We can also ensure that styles that are only present on the initial page are removed.

Sure, I can add another test to cover that.

**Comment by SantosGuillamot** [comment]
Test to check that styles are removed added at https://github.com/WordPress/block-interactivity-experiments/pull/185/commits/9b90b11c2737fef1e858b2c86d8feca4efb179de

**Comment by SantosGuillamot** [comment]
Test to check that client-side navigation is working added at https://github.com/WordPress/block-interactivity-experiments/pull/185/commits/32ad7df9a280d19c1a56d43f43f66104d2e0a98d

**Comment by michalczaplinski** [comment]
> Indeed, one test is failing in this PR because we are not fetching the scripts after client-side navigation properly. I believe we need to fetch not only the <head> but also the <body> as explained https://github.com/WordPress/block-interactivity-experiments/pull/164#issuecomment-1473813079. Once that is solved, these tests should pass if I am not mistaken.

Hmm, I think that was not the problem because the tests are now passing. Wasn't the problem that we previously haven't updated the `wp-link` directives to be `data-wp-link` which was fixed in [f5b4bcd](https://github.com/WordPress/block-interactivity-experiments/pull/185/commits/f5b4bcd520564e9d6896837e7667fa53efe1e605)? I'm confused here.

**Comment by michalczaplinski** [comment]
Oh, I see the test is just commented out now.

**Comment by SantosGuillamot** [comment]
After merging the [changes to fetch the whole document and not only the head](https://github.com/WordPress/block-interactivity-experiments/pull/164#issuecomment-1479117982), tests are passing.

**Review by michalczaplinski — APPROVED** [review]
Awesome work Mario! 👍

**Pull request merged**
