### PR TITLE
🎨 Switch toVdom from array iteration to createTreeWalker

### PR DESCRIPTION
**Pull request by luisherranz**
I have been testing `createTreeWalker`, and it is consistently faster than the `for` we are using now: 50% in Chrome and 15% in Firefox and Safari.

This PR is not ready to merge yet. I have opened it up with my tests if anyone wants to do theirs as well. I have also recorded a video explaining what I have done so far:

<a href="https://www.loom.com/share/0b0966748b944c1cb858c45a10def67b">
    
  </a>

- https://www.loom.com/share/0b0966748b944c1cb858c45a10def67b
- https://excalidraw.com/#json=_2a96abSkBv_HWZsal2ri,XoSvfXho0gFrtutfak8Cjg
- https://stackblitz.com/edit/vitejs-vite-zyzjzm?file=index.html,main.js&terminal=dev
- https://jsbench.me/6flajfs1t9/1

I won't be able to continue with this PR in the next few days, so if anyone wants to, you can finish it: remove the tests, delete old code, etc. I haven't tested the algorithm with HTML comments either, so we would have to test that it works before merging it. We also have to start thinking about adding tests (unit and e2e), but maybe that can be done in another PR.

---

Thanks to @michalczaplinski for the HTML file generator 🙂

### CODE REVIEW

**Comment by luisherranz** [comment]
I guess that the 5 heart reactions in the opening posts mean you all like it, so I'll clean it up, resolve the conflicts and prepare it for review 🙂

**Comment by SantosGuillamot** [comment]
I loved the explanation 😁 And it seems faster, so I'm fine with pursuing this approach.

**Comment by luisherranz** [comment]
I had to make a small adjustment to the algorithm and I added e2e tests (kudos to @darerodz for helping me with those). Both are explained in the video:

<a href="https://www.loom.com/share/45610946048c43d28adafb59e681245f">
    
  </a>

https://www.loom.com/share/45610946048c43d28adafb59e681245f

Ok. This is finally ready for review! 🎉

**Review by DAreRodz — APPROVED** [review]
I think it's perfect, @luisherranz. 👌 Feel free to merge it.

**Comment by luisherranz** [comment]
Thanks David!

**Pull request merged**
